import 'package:flutter/material.dart';

class KurikulumMahasiswaPage extends StatelessWidget {
  final List<Map<String, dynamic>> kurikulumList = [
    {
      'no': 1,
      'kodeMK': 'DSI217',
      'namaMK': 'ALGORITMA DAN PEMROGRAMAN',
      'sksTotal': 2,
      'sksTatapMuka': 2,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'B+',
    },
    {
      'no': 2,
      'kodeMK': 'DSI218',
      'namaMK': 'SISTEM OPERASI',
      'sksTotal': 2,
      'sksTatapMuka': 2,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A-',
    },
    {
      'no': 3,
      'kodeMK': 'FST115',
      'namaMK': 'DASAR - DASAR SAINS DAN TEKNOLOGI',
      'sksTotal': 2,
      'sksTatapMuka': 2,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'B+',
    },
    {
      'no': 4,
      'kodeMK': 'KALKULUS',
      'namaMK': 'SISTEM OPERASI',
      'sksTotal': 3,
      'sksTatapMuka': 3,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A-',
    },
    {
      'no': 5,
      'kodeMK': 'FST116',
      'namaMK': 'TEKNOLOGI INFORMASI DAN KOMUNIKASI',
      'sksTotal': 2,
      'sksTatapMuka': 2,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 6,
      'kodeMK': 'LSI217',
      'namaMK': 'PRAKTIKUM ALGORITMA DAN PEMROGRAMAN',
      'sksTotal': 1,
      'sksTatapMuka': 0,
      'sksPraktek': 1,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'B+',
    },
    {
      'no': 7,
      'kodeMK': 'LSI218',
      'namaMK': 'PRAKTIKUM SISTEM OPERASI',
      'sksTotal': 1,
      'sksTatapMuka': 0,
      'sksPraktek': 1,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A-+',
    },
    {
      'no': 8,
      'kodeMK': 'UNJ123',
      'namaMK': 'Bahasa Inggris',
      'sksTotal': 2,
      'sksTatapMuka': 2,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 9,
      'kodeMK': 'UNS112',
      'namaMK': 'Pancasila',
      'sksTotal': 2.00,
      'sksTatapMuka': 2.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 10,
      'kodeMK': 'UNS114',
      'namaMK': 'Bahasa Indonesia',
      'sksTotal': 2.00,
      'sksTatapMuka': 2.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 11,
      'kodeMK': 'UNS211',
      'namaMK': 'Agama I',
      'sksTotal': 2.00,
      'sksTatapMuka': 2.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 1,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 12,
      'kodeMK': 'DSI126',
      'namaMK': 'MATEMATIKA DISKRIT',
      'sksTotal': 3.00,
      'sksTatapMuka': 3.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'B+',
    },
    {
      'no': 13,
      'kodeMK': 'DSI221',
      'namaMK': 'PENGANTAR BISNIS DAN MANAJEMEN',
      'sksTotal': 3.00,
      'sksTatapMuka': 3.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 14,
      'kodeMK': 'DSI224',
      'namaMK': 'BASIS DATA I',
      'sksTotal': 2.00,
      'sksTatapMuka': 2.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'B+',
    },
    {
      'no': 15,
      'kodeMK': 'DSI225',
      'namaMK': 'PENGANTAR SISTEM INFORMASI',
      'sksTotal': 3.00,
      'sksTatapMuka': 3.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 16,
      'kodeMK': 'DSI327',
      'namaMK': 'STRUKTUR DATA',
      'sksTotal': 2.00,
      'sksTatapMuka': 2.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 17,
      'kodeMK': 'DSI328',
      'namaMK': 'MATRIKS DAN TRANSFORMASI LINEAR',
      'sksTotal': 3.00,
      'sksTatapMuka': 3.00,
      'sksPraktek': 0,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'A-',
    },
    {
      'no': 18,
      'kodeMK': 'LSI224',
      'namaMK': 'PRAKTIKUM BASIS DATA I',
      'sksTotal': 1.00,
      'sksTatapMuka': 0.00,
      'sksPraktek': 1,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'A-',
    },
    {
      'no': 19,
      'kodeMK': 'LSI327',
      'namaMK': 'PRAKTIKUM STRUKTUR DATA',
      'sksTotal': 1.00,
      'sksTatapMuka': 0.00,
      'sksPraktek': 1,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'A',
    },
    {
      'no': 20,
      'kodeMK': '	UNJ124',
      'namaMK': 'KEWIRAUSAHAAN BERBASIS AGROINDUSTRI DAN LINGKUNGAN',
      'sksTotal': 3.00,
      'sksTatapMuka': 3.00,
      'sksPraktek': 0.00,
      'sksLapangan': 0,
      'sksSimulasi': 0,
      'semester': 2,
      'wajib': true,
      'nilaiTertinggi': 'B+',
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Kurikulum Mahasiswa'),
      ),
      body: SingleChildScrollView(
        scrollDirection: Axis.horizontal, // Aktifkan pengguliran horizontal
        child: DataTable(
          columns: const <DataColumn>[
            DataColumn(
              label: Text('No'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(
              label: Text('Kode MK'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(label: Text('Nama MK')),
            DataColumn(
              label: Text('SKS Total'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(
              label: Text('SKS Tatap Muka'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(
              label: Text('SKS Praktek'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(
              label: Text('SKS Lapangan'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(
              label: Text('SKS Simulasi'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(
              label: Text('Semester'),
              numeric: true, // Atribut numeric untuk mengatur lebar kolom
            ),
            DataColumn(label: Text('Wajib')),
            DataColumn(label: Text('Nilai Tertinggi')),
          ],
          rows: kurikulumList.map((kurikulum) {
            return DataRow(
              cells: <DataCell>[
                DataCell(Text('${kurikulum['no']}')),
                DataCell(Text('${kurikulum['kodeMK']}')),
                DataCell(Text('${kurikulum['namaMK']}')),
                DataCell(Text('${kurikulum['sksTotal']}')),
                DataCell(Text('${kurikulum['sksTatapMuka']}')),
                DataCell(Text('${kurikulum['sksPraktek']}')),
                DataCell(Text('${kurikulum['sksLapangan']}')),
                DataCell(Text('${kurikulum['sksSimulasi']}')),
                DataCell(Text('${kurikulum['semester']}')),
                DataCell(Text('${kurikulum['wajib'] ? 'Ya' : 'Tidak'}')),
                DataCell(Text('${kurikulum['nilaiTertinggi']}')),
              ],
            );
          }).toList(),
        ),
      ),
    );
  }
}
